#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=${1:-.env.jetson}
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

IMAGE_NAME=${IMAGE_NAME:-yolo-capsule:jetson}
CONTAINER_NAME=${CONTAINER_NAME:-yolo-capsule}
CAPSULE_MODEL=${CAPSULE_MODEL:-/app/models/trained/capsule_yolo11s_obb_best.pt}
CAPSULE_SOURCE=${CAPSULE_SOURCE:-csi:0}
CAPSULE_SECONDARY_SOURCE=${CAPSULE_SECONDARY_SOURCE:-csi:1}
CAPSULE_DEVICE=${CAPSULE_DEVICE:-0}
CAPSULE_IMGSZ=${CAPSULE_IMGSZ:-1280}
CAPSULE_EXPOSURE_US=${CAPSULE_EXPOSURE_US:-8000}
CAPSULE_ANALOG_GAIN=${CAPSULE_ANALOG_GAIN:-1.0}
CAPSULE_DIGITAL_GAIN=${CAPSULE_DIGITAL_GAIN:-1.0}
CAPSULE_HALF=${CAPSULE_HALF:-true}
CAPSULE_CONF=${CAPSULE_CONF:-0.25}
CAPSULE_IOU=${CAPSULE_IOU:-0.7}
CAPSULE_CAMERA_DEVICE=${CAPSULE_CAMERA_DEVICE:-/dev/video${CAPSULE_SOURCE}}
CAPSULE_CAPTURE_WIDTH=${CAPSULE_CAPTURE_WIDTH:-3280}
CAPSULE_CAPTURE_HEIGHT=${CAPSULE_CAPTURE_HEIGHT:-2464}
CAPSULE_CAPTURE_FPS=${CAPSULE_CAPTURE_FPS:-21}
CAPSULE_PREVIEW_WIDTH=${CAPSULE_PREVIEW_WIDTH:-1280}
CAPSULE_PREVIEW_FPS=${CAPSULE_PREVIEW_FPS:-2}
CAPSULE_PREVIEW_JPEG_QUALITY=${CAPSULE_PREVIEW_JPEG_QUALITY:-84}
CAPSULE_AUTOFOCUS=${CAPSULE_AUTOFOCUS:-true}
CAPSULE_SOLENOID_ENABLED=${CAPSULE_SOLENOID_ENABLED:-false}
CAPSULE_SOLENOID_CHIP=${CAPSULE_SOLENOID_CHIP:-mcp23017}
CAPSULE_SOLENOID_I2C_BUS=${CAPSULE_SOLENOID_I2C_BUS:-7}
CAPSULE_SOLENOID_I2C_ADDRESS=${CAPSULE_SOLENOID_I2C_ADDRESS:-0x20}
CAPSULE_SOLENOID_ACTIVE_HIGH=${CAPSULE_SOLENOID_ACTIVE_HIGH:-true}
CAPSULE_SOLENOID_INTAKE_CHANNEL=${CAPSULE_SOLENOID_INTAKE_CHANNEL:-0}
CAPSULE_SOLENOID_DISCHARGE_CHANNEL=${CAPSULE_SOLENOID_DISCHARGE_CHANNEL:-1}
CAPSULE_SOLENOID_INTAKE_SECONDS=${CAPSULE_SOLENOID_INTAKE_SECONDS:-2}
CAPSULE_SOLENOID_INSPECTION_SECONDS=${CAPSULE_SOLENOID_INSPECTION_SECONDS:-30}
CAPSULE_SOLENOID_DISCHARGE_SECONDS=${CAPSULE_SOLENOID_DISCHARGE_SECONDS:-3}
CAPSULE_SOLENOID_COOLDOWN_SECONDS=${CAPSULE_SOLENOID_COOLDOWN_SECONDS:-120}

DEVICE_ARGS=()
ARGUS_ARGS=()
GROUP_ARGS=()
if [[ -e /tmp/argus_socket ]]; then
  ARGUS_ARGS=(-v /tmp/argus_socket:/tmp/argus_socket)
fi

for group_name in video render i2c; do
  group_entry=$(getent group "$group_name" || true)
  if [[ -n "$group_entry" ]]; then
    IFS=: read -r _ _ group_id _ <<< "$group_entry"
    GROUP_ARGS+=(--group-add "$group_id")
  fi
done

if [[ "$CAPSULE_SOURCE" =~ ^[0-9]+$ ]]; then
  if [[ ! -e "$CAPSULE_CAMERA_DEVICE" ]]; then
    echo "Camera device not found: $CAPSULE_CAMERA_DEVICE" >&2
    echo "Set CAPSULE_CAMERA_DEVICE in $ENV_FILE, or set CAPSULE_SOURCE to a mounted video file." >&2
    exit 1
  fi
  DEVICE_ARGS+=(--device "$CAPSULE_CAMERA_DEVICE:$CAPSULE_CAMERA_DEVICE")
fi

if [[ ${CAPSULE_SOLENOID_ENABLED,,} =~ ^(1|true|yes|on)$ ]]; then
  solenoid_i2c_device=/dev/i2c-${CAPSULE_SOLENOID_I2C_BUS}
  [[ -e $solenoid_i2c_device ]] || { echo "Solenoid I2C device not found: $solenoid_i2c_device" >&2; exit 1; }
  DEVICE_ARGS+=(--device "$solenoid_i2c_device:$solenoid_i2c_device")
fi

if [[ "$CAPSULE_SECONDARY_SOURCE" =~ ^[0-9]+$ ]]; then
  secondary_device=/dev/video${CAPSULE_SECONDARY_SOURCE}
  [[ -e $secondary_device ]] || { echo "Camera device not found: $secondary_device" >&2; exit 1; }
  DEVICE_ARGS+=(--device "$secondary_device:$secondary_device")
fi

if [[ ${CAPSULE_AUTOFOCUS,,} =~ ^(1|true|yes|on)$ ]]; then
  for i2c_device in /dev/i2c-9 /dev/i2c-10; do
    [[ -e $i2c_device ]] || { echo "Autofocus device not found: $i2c_device" >&2; exit 1; }
    DEVICE_ARGS+=(--device "$i2c_device:$i2c_device")
  done
fi

docker run --rm -it \
  --name "$CONTAINER_NAME" \
  --runtime nvidia \
  --network host \
  --ipc host \
  "${DEVICE_ARGS[@]}" \
  "${ARGUS_ARGS[@]}" \
  "${GROUP_ARGS[@]}" \
  -e CAPSULE_MODEL="$CAPSULE_MODEL" \
  -e CAPSULE_SOURCE="$CAPSULE_SOURCE" \
  -e CAPSULE_SECONDARY_SOURCE="$CAPSULE_SECONDARY_SOURCE" \
  -e CAPSULE_DEVICE="$CAPSULE_DEVICE" \
  -e CAPSULE_IMGSZ="$CAPSULE_IMGSZ" \
  -e CAPSULE_CAPTURE_WIDTH="$CAPSULE_CAPTURE_WIDTH" \
  -e CAPSULE_CAPTURE_HEIGHT="$CAPSULE_CAPTURE_HEIGHT" \
  -e CAPSULE_CAPTURE_FPS="$CAPSULE_CAPTURE_FPS" \
  -e CAPSULE_EXPOSURE_US="$CAPSULE_EXPOSURE_US" \
  -e CAPSULE_ANALOG_GAIN="$CAPSULE_ANALOG_GAIN" \
  -e CAPSULE_DIGITAL_GAIN="$CAPSULE_DIGITAL_GAIN" \
  -e CAPSULE_HALF="$CAPSULE_HALF" \
  -e CAPSULE_CONF="$CAPSULE_CONF" \
  -e CAPSULE_IOU="$CAPSULE_IOU" \
  -e CAPSULE_PREVIEW_WIDTH="$CAPSULE_PREVIEW_WIDTH" \
  -e CAPSULE_PREVIEW_FPS="$CAPSULE_PREVIEW_FPS" \
  -e CAPSULE_PREVIEW_JPEG_QUALITY="$CAPSULE_PREVIEW_JPEG_QUALITY" \
  -e CAPSULE_AUTOFOCUS="$CAPSULE_AUTOFOCUS" \
  -e CAPSULE_SOLENOID_ENABLED="$CAPSULE_SOLENOID_ENABLED" \
  -e CAPSULE_SOLENOID_CHIP="$CAPSULE_SOLENOID_CHIP" \
  -e CAPSULE_SOLENOID_I2C_BUS="$CAPSULE_SOLENOID_I2C_BUS" \
  -e CAPSULE_SOLENOID_I2C_ADDRESS="$CAPSULE_SOLENOID_I2C_ADDRESS" \
  -e CAPSULE_SOLENOID_ACTIVE_HIGH="$CAPSULE_SOLENOID_ACTIVE_HIGH" \
  -e CAPSULE_SOLENOID_INTAKE_CHANNEL="$CAPSULE_SOLENOID_INTAKE_CHANNEL" \
  -e CAPSULE_SOLENOID_DISCHARGE_CHANNEL="$CAPSULE_SOLENOID_DISCHARGE_CHANNEL" \
  -e CAPSULE_SOLENOID_INTAKE_SECONDS="$CAPSULE_SOLENOID_INTAKE_SECONDS" \
  -e CAPSULE_SOLENOID_INSPECTION_SECONDS="$CAPSULE_SOLENOID_INSPECTION_SECONDS" \
  -e CAPSULE_SOLENOID_DISCHARGE_SECONDS="$CAPSULE_SOLENOID_DISCHARGE_SECONDS" \
  -e CAPSULE_SOLENOID_COOLDOWN_SECONDS="$CAPSULE_SOLENOID_COOLDOWN_SECONDS" \
  -e YOLO_CONFIG_DIR=/tmp/ultralytics \
  -e MPLCONFIGDIR=/tmp/matplotlib \
  -v "$PWD/src:/app/src:ro" \
  -v "$PWD/configs:/app/configs:ro" \
  -v "$PWD/data:/app/data" \
  -v "$PWD/models:/app/models" \
  -v "$PWD/runs:/app/runs" \
  "$IMAGE_NAME"
